/********************************************************************************
** Form generated from reading UI file 'keyboardwaVhCT.ui'
**
** Created by: Qt User Interface Compiler version 5.15.7
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef KEYBOARDWAVHCT_H
#define KEYBOARDWAVHCT_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Keyboard
{
public:
    QLabel *label_1;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_0;
    QLabel *label_minus;
    QLabel *label_equal;
    QLabel *label_backspace;
    QLabel *label_14;
    QLabel *label_tab;
    QLabel *label_q;
    QLabel *label_w;
    QLabel *label_e;
    QLabel *label_r;
    QLabel *label_t;
    QLabel *label_y;
    QLabel *label_u;
    QLabel *label_i;
    QLabel *label_o;
    QLabel *label_p;
    QLabel *label_leftbrace;
    QLabel *label_rightbrace;
    QLabel *label_backslash;
    QLabel *label_a;
    QLabel *label_s;
    QLabel *label_d;
    QLabel *label_f;
    QLabel *label_g;
    QLabel *label_h;
    QLabel *label_j;
    QLabel *label_k;
    QLabel *label_l;
    QLabel *label_semicolon;
    QLabel *label_apostrophe;
    QLabel *label_enter;
    QLabel *label_capslock;
    QLabel *label_leftshift;
    QLabel *label_z;
    QLabel *label_x;
    QLabel *label_c;
    QLabel *label_v;
    QLabel *label_b;
    QLabel *label_n;
    QLabel *label_m;
    QLabel *label_comma;
    QLabel *label_dot;
    QLabel *label_slash;
    QLabel *label_rightshift;
    QLabel *label_leftctrl;
    QLabel *label_55;
    QLabel *label_esc;
    QLabel *label_f1;
    QLabel *label_f2;
    QLabel *label_f3;
    QLabel *label_f4;
    QLabel *label_f5;
    QLabel *label_f6;
    QLabel *label_f7;
    QLabel *label_f8;
    QLabel *label_f9;
    QLabel *label_f10;
    QLabel *label_f11;
    QLabel *label_f12;
    QLabel *label_delete;
    QLabel *label_macro;
    QLabel *label_leftalt;
    QLabel *label_space;
    QLabel *label_rightalt;
    QLabel *label_rightctrl;
    QLabel *label_left;
    QLabel *label_right;
    QLabel *label_up;
    QLabel *label_down;
    QWidget *widget;

    void setupUi(QWidget *Keyboard)
    {
        if (Keyboard->objectName().isEmpty())
            Keyboard->setObjectName(QString::fromUtf8("Keyboard"));
        Keyboard->resize(728, 288);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Keyboard->sizePolicy().hasHeightForWidth());
        Keyboard->setSizePolicy(sizePolicy);
        Keyboard->setMinimumSize(QSize(728, 288));
        Keyboard->setMaximumSize(QSize(728, 288));
        Keyboard->setStyleSheet(QString::fromUtf8("background-color: rgba(0,0,0,0.5);"));
        label_1 = new QLabel(Keyboard);
        label_1->setObjectName(QString::fromUtf8("label_1"));
        label_1->setGeometry(QRect(60, 40, 41, 41));
        QFont font;
        font.setFamily(QString::fromUtf8("Consolas"));
        font.setBold(false);
        font.setWeight(50);
        font.setKerning(true);
        font.setStyleStrategy(QFont::PreferDefault);
        label_1->setFont(font);
        label_1->setFrameShape(QFrame::Panel);
        label_1->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(Keyboard);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(110, 40, 41, 41));
        label_2->setFont(font);
        label_2->setFrameShape(QFrame::Panel);
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(Keyboard);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(160, 40, 41, 41));
        label_3->setFont(font);
        label_3->setFrameShape(QFrame::Panel);
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(Keyboard);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(210, 40, 41, 41));
        label_4->setFont(font);
        label_4->setFrameShape(QFrame::Panel);
        label_4->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(Keyboard);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(260, 40, 41, 41));
        label_5->setFont(font);
        label_5->setFrameShape(QFrame::Panel);
        label_5->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(Keyboard);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(310, 40, 41, 41));
        label_6->setFont(font);
        label_6->setFrameShape(QFrame::Panel);
        label_6->setAlignment(Qt::AlignCenter);
        label_7 = new QLabel(Keyboard);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(360, 40, 41, 41));
        label_7->setFont(font);
        label_7->setFrameShape(QFrame::Panel);
        label_7->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(Keyboard);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(410, 40, 41, 41));
        label_8->setFont(font);
        label_8->setFrameShape(QFrame::Panel);
        label_8->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(Keyboard);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(460, 40, 41, 41));
        label_9->setFont(font);
        label_9->setFrameShape(QFrame::Panel);
        label_9->setAlignment(Qt::AlignCenter);
        label_0 = new QLabel(Keyboard);
        label_0->setObjectName(QString::fromUtf8("label_0"));
        label_0->setGeometry(QRect(510, 40, 41, 41));
        label_0->setFont(font);
        label_0->setFrameShape(QFrame::Panel);
        label_0->setAlignment(Qt::AlignCenter);
        label_minus = new QLabel(Keyboard);
        label_minus->setObjectName(QString::fromUtf8("label_minus"));
        label_minus->setGeometry(QRect(560, 40, 41, 41));
        label_minus->setFont(font);
        label_minus->setFrameShape(QFrame::Panel);
        label_minus->setAlignment(Qt::AlignCenter);
        label_equal = new QLabel(Keyboard);
        label_equal->setObjectName(QString::fromUtf8("label_equal"));
        label_equal->setGeometry(QRect(610, 40, 41, 41));
        label_equal->setFont(font);
        label_equal->setFrameShape(QFrame::Panel);
        label_equal->setAlignment(Qt::AlignCenter);
        label_backspace = new QLabel(Keyboard);
        label_backspace->setObjectName(QString::fromUtf8("label_backspace"));
        label_backspace->setGeometry(QRect(660, 40, 61, 41));
        label_backspace->setFont(font);
        label_backspace->setFrameShape(QFrame::Panel);
        label_backspace->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(Keyboard);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 40, 41, 41));
        label_14->setFont(font);
        label_14->setFrameShape(QFrame::Panel);
        label_14->setAlignment(Qt::AlignCenter);
        label_tab = new QLabel(Keyboard);
        label_tab->setObjectName(QString::fromUtf8("label_tab"));
        label_tab->setGeometry(QRect(10, 90, 61, 41));
        label_tab->setFont(font);
        label_tab->setFrameShape(QFrame::Panel);
        label_tab->setAlignment(Qt::AlignCenter);
        label_q = new QLabel(Keyboard);
        label_q->setObjectName(QString::fromUtf8("label_q"));
        label_q->setGeometry(QRect(80, 90, 41, 41));
        label_q->setFont(font);
        label_q->setFrameShape(QFrame::Panel);
        label_q->setAlignment(Qt::AlignCenter);
        label_w = new QLabel(Keyboard);
        label_w->setObjectName(QString::fromUtf8("label_w"));
        label_w->setGeometry(QRect(130, 90, 41, 41));
        label_w->setFont(font);
        label_w->setFrameShape(QFrame::Panel);
        label_w->setAlignment(Qt::AlignCenter);
        label_e = new QLabel(Keyboard);
        label_e->setObjectName(QString::fromUtf8("label_e"));
        label_e->setGeometry(QRect(180, 90, 41, 41));
        label_e->setFont(font);
        label_e->setFrameShape(QFrame::Panel);
        label_e->setAlignment(Qt::AlignCenter);
        label_r = new QLabel(Keyboard);
        label_r->setObjectName(QString::fromUtf8("label_r"));
        label_r->setGeometry(QRect(230, 90, 41, 41));
        label_r->setFont(font);
        label_r->setFrameShape(QFrame::Panel);
        label_r->setAlignment(Qt::AlignCenter);
        label_t = new QLabel(Keyboard);
        label_t->setObjectName(QString::fromUtf8("label_t"));
        label_t->setGeometry(QRect(280, 90, 41, 41));
        label_t->setFont(font);
        label_t->setFrameShape(QFrame::Panel);
        label_t->setAlignment(Qt::AlignCenter);
        label_y = new QLabel(Keyboard);
        label_y->setObjectName(QString::fromUtf8("label_y"));
        label_y->setGeometry(QRect(330, 90, 41, 41));
        label_y->setFont(font);
        label_y->setFrameShape(QFrame::Panel);
        label_y->setAlignment(Qt::AlignCenter);
        label_u = new QLabel(Keyboard);
        label_u->setObjectName(QString::fromUtf8("label_u"));
        label_u->setGeometry(QRect(380, 90, 41, 41));
        label_u->setFont(font);
        label_u->setFrameShape(QFrame::Panel);
        label_u->setAlignment(Qt::AlignCenter);
        label_i = new QLabel(Keyboard);
        label_i->setObjectName(QString::fromUtf8("label_i"));
        label_i->setGeometry(QRect(430, 90, 41, 41));
        label_i->setFont(font);
        label_i->setFrameShape(QFrame::Panel);
        label_i->setAlignment(Qt::AlignCenter);
        label_o = new QLabel(Keyboard);
        label_o->setObjectName(QString::fromUtf8("label_o"));
        label_o->setGeometry(QRect(480, 90, 41, 41));
        label_o->setFont(font);
        label_o->setFrameShape(QFrame::Panel);
        label_o->setAlignment(Qt::AlignCenter);
        label_p = new QLabel(Keyboard);
        label_p->setObjectName(QString::fromUtf8("label_p"));
        label_p->setGeometry(QRect(530, 90, 41, 41));
        label_p->setFont(font);
        label_p->setFrameShape(QFrame::Panel);
        label_p->setAlignment(Qt::AlignCenter);
        label_leftbrace = new QLabel(Keyboard);
        label_leftbrace->setObjectName(QString::fromUtf8("label_leftbrace"));
        label_leftbrace->setGeometry(QRect(580, 90, 41, 41));
        label_leftbrace->setFont(font);
        label_leftbrace->setFrameShape(QFrame::Panel);
        label_leftbrace->setAlignment(Qt::AlignCenter);
        label_rightbrace = new QLabel(Keyboard);
        label_rightbrace->setObjectName(QString::fromUtf8("label_rightbrace"));
        label_rightbrace->setGeometry(QRect(630, 90, 41, 41));
        label_rightbrace->setFont(font);
        label_rightbrace->setFrameShape(QFrame::Panel);
        label_rightbrace->setAlignment(Qt::AlignCenter);
        label_backslash = new QLabel(Keyboard);
        label_backslash->setObjectName(QString::fromUtf8("label_backslash"));
        label_backslash->setGeometry(QRect(680, 90, 41, 41));
        label_backslash->setFont(font);
        label_backslash->setFrameShape(QFrame::Panel);
        label_backslash->setAlignment(Qt::AlignCenter);
        label_a = new QLabel(Keyboard);
        label_a->setObjectName(QString::fromUtf8("label_a"));
        label_a->setGeometry(QRect(100, 140, 41, 41));
        label_a->setFont(font);
        label_a->setFrameShape(QFrame::Panel);
        label_a->setAlignment(Qt::AlignCenter);
        label_s = new QLabel(Keyboard);
        label_s->setObjectName(QString::fromUtf8("label_s"));
        label_s->setGeometry(QRect(150, 140, 41, 41));
        label_s->setFont(font);
        label_s->setFrameShape(QFrame::Panel);
        label_s->setAlignment(Qt::AlignCenter);
        label_d = new QLabel(Keyboard);
        label_d->setObjectName(QString::fromUtf8("label_d"));
        label_d->setGeometry(QRect(200, 140, 41, 41));
        label_d->setFont(font);
        label_d->setFrameShape(QFrame::Panel);
        label_d->setAlignment(Qt::AlignCenter);
        label_f = new QLabel(Keyboard);
        label_f->setObjectName(QString::fromUtf8("label_f"));
        label_f->setGeometry(QRect(250, 140, 41, 41));
        label_f->setFont(font);
        label_f->setFrameShape(QFrame::Panel);
        label_f->setAlignment(Qt::AlignCenter);
        label_g = new QLabel(Keyboard);
        label_g->setObjectName(QString::fromUtf8("label_g"));
        label_g->setGeometry(QRect(300, 140, 41, 41));
        label_g->setFont(font);
        label_g->setFrameShape(QFrame::Panel);
        label_g->setAlignment(Qt::AlignCenter);
        label_h = new QLabel(Keyboard);
        label_h->setObjectName(QString::fromUtf8("label_h"));
        label_h->setGeometry(QRect(350, 140, 41, 41));
        label_h->setFont(font);
        label_h->setFrameShape(QFrame::Panel);
        label_h->setAlignment(Qt::AlignCenter);
        label_j = new QLabel(Keyboard);
        label_j->setObjectName(QString::fromUtf8("label_j"));
        label_j->setGeometry(QRect(400, 140, 41, 41));
        label_j->setFont(font);
        label_j->setFrameShape(QFrame::Panel);
        label_j->setAlignment(Qt::AlignCenter);
        label_k = new QLabel(Keyboard);
        label_k->setObjectName(QString::fromUtf8("label_k"));
        label_k->setGeometry(QRect(450, 140, 41, 41));
        label_k->setFont(font);
        label_k->setFrameShape(QFrame::Panel);
        label_k->setAlignment(Qt::AlignCenter);
        label_l = new QLabel(Keyboard);
        label_l->setObjectName(QString::fromUtf8("label_l"));
        label_l->setGeometry(QRect(500, 140, 41, 41));
        label_l->setFont(font);
        label_l->setFrameShape(QFrame::Panel);
        label_l->setAlignment(Qt::AlignCenter);
        label_semicolon = new QLabel(Keyboard);
        label_semicolon->setObjectName(QString::fromUtf8("label_semicolon"));
        label_semicolon->setGeometry(QRect(550, 140, 41, 41));
        label_semicolon->setFont(font);
        label_semicolon->setFrameShape(QFrame::Panel);
        label_semicolon->setAlignment(Qt::AlignCenter);
        label_apostrophe = new QLabel(Keyboard);
        label_apostrophe->setObjectName(QString::fromUtf8("label_apostrophe"));
        label_apostrophe->setGeometry(QRect(600, 140, 41, 41));
        label_apostrophe->setFont(font);
        label_apostrophe->setFrameShape(QFrame::Panel);
        label_apostrophe->setAlignment(Qt::AlignCenter);
        label_enter = new QLabel(Keyboard);
        label_enter->setObjectName(QString::fromUtf8("label_enter"));
        label_enter->setGeometry(QRect(650, 140, 71, 41));
        label_enter->setFont(font);
        label_enter->setFrameShape(QFrame::Panel);
        label_enter->setAlignment(Qt::AlignCenter);
        label_capslock = new QLabel(Keyboard);
        label_capslock->setObjectName(QString::fromUtf8("label_capslock"));
        label_capslock->setGeometry(QRect(10, 140, 81, 41));
        label_capslock->setFont(font);
        label_capslock->setFrameShape(QFrame::Panel);
        label_capslock->setAlignment(Qt::AlignCenter);
        label_leftshift = new QLabel(Keyboard);
        label_leftshift->setObjectName(QString::fromUtf8("label_leftshift"));
        label_leftshift->setGeometry(QRect(10, 190, 101, 41));
        label_leftshift->setFont(font);
        label_leftshift->setFrameShape(QFrame::Panel);
        label_leftshift->setAlignment(Qt::AlignCenter);
        label_z = new QLabel(Keyboard);
        label_z->setObjectName(QString::fromUtf8("label_z"));
        label_z->setGeometry(QRect(120, 190, 41, 41));
        label_z->setFont(font);
        label_z->setFrameShape(QFrame::Panel);
        label_z->setAlignment(Qt::AlignCenter);
        label_x = new QLabel(Keyboard);
        label_x->setObjectName(QString::fromUtf8("label_x"));
        label_x->setGeometry(QRect(170, 190, 41, 41));
        label_x->setFont(font);
        label_x->setFrameShape(QFrame::Panel);
        label_x->setAlignment(Qt::AlignCenter);
        label_c = new QLabel(Keyboard);
        label_c->setObjectName(QString::fromUtf8("label_c"));
        label_c->setGeometry(QRect(220, 190, 41, 41));
        label_c->setFont(font);
        label_c->setFrameShape(QFrame::Panel);
        label_c->setAlignment(Qt::AlignCenter);
        label_v = new QLabel(Keyboard);
        label_v->setObjectName(QString::fromUtf8("label_v"));
        label_v->setGeometry(QRect(270, 190, 41, 41));
        label_v->setFont(font);
        label_v->setFrameShape(QFrame::Panel);
        label_v->setAlignment(Qt::AlignCenter);
        label_b = new QLabel(Keyboard);
        label_b->setObjectName(QString::fromUtf8("label_b"));
        label_b->setGeometry(QRect(320, 190, 41, 41));
        label_b->setFont(font);
        label_b->setFrameShape(QFrame::Panel);
        label_b->setAlignment(Qt::AlignCenter);
        label_n = new QLabel(Keyboard);
        label_n->setObjectName(QString::fromUtf8("label_n"));
        label_n->setGeometry(QRect(370, 190, 41, 41));
        label_n->setFont(font);
        label_n->setFrameShape(QFrame::Panel);
        label_n->setAlignment(Qt::AlignCenter);
        label_m = new QLabel(Keyboard);
        label_m->setObjectName(QString::fromUtf8("label_m"));
        label_m->setGeometry(QRect(420, 190, 41, 41));
        label_m->setFont(font);
        label_m->setFrameShape(QFrame::Panel);
        label_m->setAlignment(Qt::AlignCenter);
        label_comma = new QLabel(Keyboard);
        label_comma->setObjectName(QString::fromUtf8("label_comma"));
        label_comma->setGeometry(QRect(470, 190, 41, 41));
        label_comma->setFont(font);
        label_comma->setFrameShape(QFrame::Panel);
        label_comma->setAlignment(Qt::AlignCenter);
        label_dot = new QLabel(Keyboard);
        label_dot->setObjectName(QString::fromUtf8("label_dot"));
        label_dot->setGeometry(QRect(520, 190, 41, 41));
        label_dot->setFont(font);
        label_dot->setFrameShape(QFrame::Panel);
        label_dot->setAlignment(Qt::AlignCenter);
        label_slash = new QLabel(Keyboard);
        label_slash->setObjectName(QString::fromUtf8("label_slash"));
        label_slash->setGeometry(QRect(570, 190, 41, 41));
        label_slash->setFont(font);
        label_slash->setFrameShape(QFrame::Panel);
        label_slash->setAlignment(Qt::AlignCenter);
        label_rightshift = new QLabel(Keyboard);
        label_rightshift->setObjectName(QString::fromUtf8("label_rightshift"));
        label_rightshift->setGeometry(QRect(620, 190, 101, 41));
        label_rightshift->setFont(font);
        label_rightshift->setFrameShape(QFrame::Panel);
        label_rightshift->setAlignment(Qt::AlignCenter);
        label_leftctrl = new QLabel(Keyboard);
        label_leftctrl->setObjectName(QString::fromUtf8("label_leftctrl"));
        label_leftctrl->setGeometry(QRect(10, 240, 61, 41));
        label_leftctrl->setFont(font);
        label_leftctrl->setFrameShape(QFrame::Panel);
        label_leftctrl->setAlignment(Qt::AlignCenter);
        label_55 = new QLabel(Keyboard);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(80, 240, 41, 41));
        label_55->setFont(font);
        label_55->setFrameShape(QFrame::Panel);
        label_55->setAlignment(Qt::AlignCenter);
        label_esc = new QLabel(Keyboard);
        label_esc->setObjectName(QString::fromUtf8("label_esc"));
        label_esc->setGeometry(QRect(10, 10, 41, 21));
        label_esc->setFont(font);
        label_esc->setFrameShape(QFrame::Panel);
        label_esc->setAlignment(Qt::AlignCenter);
        label_f1 = new QLabel(Keyboard);
        label_f1->setObjectName(QString::fromUtf8("label_f1"));
        label_f1->setGeometry(QRect(60, 10, 41, 21));
        label_f1->setFont(font);
        label_f1->setFrameShape(QFrame::Panel);
        label_f1->setAlignment(Qt::AlignCenter);
        label_f2 = new QLabel(Keyboard);
        label_f2->setObjectName(QString::fromUtf8("label_f2"));
        label_f2->setGeometry(QRect(110, 10, 41, 21));
        label_f2->setFont(font);
        label_f2->setFrameShape(QFrame::Panel);
        label_f2->setAlignment(Qt::AlignCenter);
        label_f3 = new QLabel(Keyboard);
        label_f3->setObjectName(QString::fromUtf8("label_f3"));
        label_f3->setGeometry(QRect(160, 10, 41, 21));
        label_f3->setFont(font);
        label_f3->setFrameShape(QFrame::Panel);
        label_f3->setAlignment(Qt::AlignCenter);
        label_f4 = new QLabel(Keyboard);
        label_f4->setObjectName(QString::fromUtf8("label_f4"));
        label_f4->setGeometry(QRect(210, 10, 41, 21));
        label_f4->setFont(font);
        label_f4->setFrameShape(QFrame::Panel);
        label_f4->setAlignment(Qt::AlignCenter);
        label_f5 = new QLabel(Keyboard);
        label_f5->setObjectName(QString::fromUtf8("label_f5"));
        label_f5->setGeometry(QRect(260, 10, 41, 21));
        label_f5->setFont(font);
        label_f5->setFrameShape(QFrame::Panel);
        label_f5->setAlignment(Qt::AlignCenter);
        label_f6 = new QLabel(Keyboard);
        label_f6->setObjectName(QString::fromUtf8("label_f6"));
        label_f6->setGeometry(QRect(310, 10, 41, 21));
        label_f6->setFont(font);
        label_f6->setFrameShape(QFrame::Panel);
        label_f6->setAlignment(Qt::AlignCenter);
        label_f7 = new QLabel(Keyboard);
        label_f7->setObjectName(QString::fromUtf8("label_f7"));
        label_f7->setGeometry(QRect(360, 10, 41, 21));
        label_f7->setFont(font);
        label_f7->setFrameShape(QFrame::Panel);
        label_f7->setAlignment(Qt::AlignCenter);
        label_f8 = new QLabel(Keyboard);
        label_f8->setObjectName(QString::fromUtf8("label_f8"));
        label_f8->setGeometry(QRect(410, 10, 41, 21));
        label_f8->setFont(font);
        label_f8->setFrameShape(QFrame::Panel);
        label_f8->setAlignment(Qt::AlignCenter);
        label_f9 = new QLabel(Keyboard);
        label_f9->setObjectName(QString::fromUtf8("label_f9"));
        label_f9->setGeometry(QRect(460, 10, 41, 21));
        label_f9->setFont(font);
        label_f9->setFrameShape(QFrame::Panel);
        label_f9->setAlignment(Qt::AlignCenter);
        label_f10 = new QLabel(Keyboard);
        label_f10->setObjectName(QString::fromUtf8("label_f10"));
        label_f10->setGeometry(QRect(510, 10, 41, 21));
        label_f10->setFont(font);
        label_f10->setFrameShape(QFrame::Panel);
        label_f10->setAlignment(Qt::AlignCenter);
        label_f11 = new QLabel(Keyboard);
        label_f11->setObjectName(QString::fromUtf8("label_f11"));
        label_f11->setGeometry(QRect(560, 10, 41, 21));
        label_f11->setFont(font);
        label_f11->setFrameShape(QFrame::Panel);
        label_f11->setAlignment(Qt::AlignCenter);
        label_f12 = new QLabel(Keyboard);
        label_f12->setObjectName(QString::fromUtf8("label_f12"));
        label_f12->setGeometry(QRect(610, 10, 41, 21));
        label_f12->setFont(font);
        label_f12->setFrameShape(QFrame::Panel);
        label_f12->setAlignment(Qt::AlignCenter);
        label_delete = new QLabel(Keyboard);
        label_delete->setObjectName(QString::fromUtf8("label_delete"));
        label_delete->setGeometry(QRect(660, 10, 61, 21));
        label_delete->setFont(font);
        label_delete->setFrameShape(QFrame::Panel);
        label_delete->setAlignment(Qt::AlignCenter);
        label_macro = new QLabel(Keyboard);
        label_macro->setObjectName(QString::fromUtf8("label_macro"));
        label_macro->setGeometry(QRect(130, 240, 41, 41));
        label_macro->setFont(font);
        label_macro->setFrameShape(QFrame::Panel);
        label_macro->setAlignment(Qt::AlignCenter);
        label_leftalt = new QLabel(Keyboard);
        label_leftalt->setObjectName(QString::fromUtf8("label_leftalt"));
        label_leftalt->setGeometry(QRect(180, 240, 41, 41));
        label_leftalt->setFont(font);
        label_leftalt->setFrameShape(QFrame::Panel);
        label_leftalt->setAlignment(Qt::AlignCenter);
        label_space = new QLabel(Keyboard);
        label_space->setObjectName(QString::fromUtf8("label_space"));
        label_space->setGeometry(QRect(230, 240, 231, 41));
        label_space->setFont(font);
        label_space->setFrameShape(QFrame::Panel);
        label_space->setAlignment(Qt::AlignCenter);
        label_rightalt = new QLabel(Keyboard);
        label_rightalt->setObjectName(QString::fromUtf8("label_rightalt"));
        label_rightalt->setGeometry(QRect(470, 240, 41, 41));
        label_rightalt->setFont(font);
        label_rightalt->setFrameShape(QFrame::Panel);
        label_rightalt->setAlignment(Qt::AlignCenter);
        label_rightctrl = new QLabel(Keyboard);
        label_rightctrl->setObjectName(QString::fromUtf8("label_rightctrl"));
        label_rightctrl->setGeometry(QRect(520, 240, 41, 41));
        label_rightctrl->setFont(font);
        label_rightctrl->setFrameShape(QFrame::Panel);
        label_rightctrl->setAlignment(Qt::AlignCenter);
        label_left = new QLabel(Keyboard);
        label_left->setObjectName(QString::fromUtf8("label_left"));
        label_left->setGeometry(QRect(570, 240, 41, 41));
        label_left->setFont(font);
        label_left->setFrameShape(QFrame::Panel);
        label_left->setAlignment(Qt::AlignCenter);
        label_right = new QLabel(Keyboard);
        label_right->setObjectName(QString::fromUtf8("label_right"));
        label_right->setGeometry(QRect(680, 240, 41, 41));
        label_right->setFont(font);
        label_right->setFrameShape(QFrame::Panel);
        label_right->setAlignment(Qt::AlignCenter);
        label_up = new QLabel(Keyboard);
        label_up->setObjectName(QString::fromUtf8("label_up"));
        label_up->setGeometry(QRect(620, 240, 51, 21));
        label_up->setFont(font);
        label_up->setFrameShape(QFrame::Panel);
        label_up->setAlignment(Qt::AlignCenter);
        label_down = new QLabel(Keyboard);
        label_down->setObjectName(QString::fromUtf8("label_down"));
        label_down->setGeometry(QRect(620, 260, 51, 21));
        label_down->setFont(font);
        label_down->setFrameShape(QFrame::Panel);
        label_down->setAlignment(Qt::AlignCenter);
        widget = new QWidget(Keyboard);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(0, 0, 731, 291));
        widget->raise();
        label_1->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_0->raise();
        label_minus->raise();
        label_equal->raise();
        label_backspace->raise();
        label_14->raise();
        label_tab->raise();
        label_q->raise();
        label_w->raise();
        label_e->raise();
        label_r->raise();
        label_t->raise();
        label_y->raise();
        label_u->raise();
        label_i->raise();
        label_o->raise();
        label_p->raise();
        label_leftbrace->raise();
        label_rightbrace->raise();
        label_backslash->raise();
        label_a->raise();
        label_s->raise();
        label_d->raise();
        label_g->raise();
        label_h->raise();
        label_j->raise();
        label_k->raise();
        label_l->raise();
        label_semicolon->raise();
        label_apostrophe->raise();
        label_enter->raise();
        label_capslock->raise();
        label_leftshift->raise();
        label_f->raise();
        label_z->raise();
        label_x->raise();
        label_c->raise();
        label_v->raise();
        label_b->raise();
        label_n->raise();
        label_m->raise();
        label_comma->raise();
        label_dot->raise();
        label_slash->raise();
        label_rightshift->raise();
        label_leftctrl->raise();
        label_55->raise();
        label_esc->raise();
        label_f1->raise();
        label_f2->raise();
        label_f3->raise();
        label_f4->raise();
        label_f5->raise();
        label_f6->raise();
        label_f7->raise();
        label_f8->raise();
        label_f9->raise();
        label_f10->raise();
        label_f11->raise();
        label_f12->raise();
        label_delete->raise();
        label_macro->raise();
        label_leftalt->raise();
        label_space->raise();
        label_rightalt->raise();
        label_rightctrl->raise();
        label_left->raise();
        label_right->raise();
        label_up->raise();
        label_down->raise();

        retranslateUi(Keyboard);

        QMetaObject::connectSlotsByName(Keyboard);
    } // setupUi

    void retranslateUi(QWidget *Keyboard)
    {
        Keyboard->setWindowTitle(QCoreApplication::translate("Keyboard", "Form", nullptr));
        label_1->setText(QCoreApplication::translate("Keyboard", "1", nullptr));
        label_2->setText(QCoreApplication::translate("Keyboard", "2", nullptr));
        label_3->setText(QCoreApplication::translate("Keyboard", "3", nullptr));
        label_4->setText(QCoreApplication::translate("Keyboard", "4", nullptr));
        label_5->setText(QCoreApplication::translate("Keyboard", "5", nullptr));
        label_6->setText(QCoreApplication::translate("Keyboard", "6", nullptr));
        label_7->setText(QCoreApplication::translate("Keyboard", "7", nullptr));
        label_8->setText(QCoreApplication::translate("Keyboard", "8", nullptr));
        label_9->setText(QCoreApplication::translate("Keyboard", "9", nullptr));
        label_0->setText(QCoreApplication::translate("Keyboard", "0", nullptr));
        label_minus->setText(QCoreApplication::translate("Keyboard", "-", nullptr));
        label_equal->setText(QCoreApplication::translate("Keyboard", "=", nullptr));
        label_backspace->setText(QCoreApplication::translate("Keyboard", "back<br>space", nullptr));
        label_14->setText(QCoreApplication::translate("Keyboard", "`", nullptr));
        label_tab->setText(QCoreApplication::translate("Keyboard", "tab", nullptr));
        label_q->setText(QCoreApplication::translate("Keyboard", "q", nullptr));
        label_w->setText(QCoreApplication::translate("Keyboard", "w", nullptr));
        label_e->setText(QCoreApplication::translate("Keyboard", "e", nullptr));
        label_r->setText(QCoreApplication::translate("Keyboard", "r", nullptr));
        label_t->setText(QCoreApplication::translate("Keyboard", "t", nullptr));
        label_y->setText(QCoreApplication::translate("Keyboard", "y", nullptr));
        label_u->setText(QCoreApplication::translate("Keyboard", "u", nullptr));
        label_i->setText(QCoreApplication::translate("Keyboard", "i", nullptr));
        label_o->setText(QCoreApplication::translate("Keyboard", "o", nullptr));
        label_p->setText(QCoreApplication::translate("Keyboard", "p", nullptr));
        label_leftbrace->setText(QCoreApplication::translate("Keyboard", "[", nullptr));
        label_rightbrace->setText(QCoreApplication::translate("Keyboard", "]", nullptr));
        label_backslash->setText(QCoreApplication::translate("Keyboard", "\\", nullptr));
        label_a->setText(QCoreApplication::translate("Keyboard", "a", nullptr));
        label_s->setText(QCoreApplication::translate("Keyboard", "s", nullptr));
        label_d->setText(QCoreApplication::translate("Keyboard", "d", nullptr));
        label_f->setText(QCoreApplication::translate("Keyboard", "f", nullptr));
        label_g->setText(QCoreApplication::translate("Keyboard", "g", nullptr));
        label_h->setText(QCoreApplication::translate("Keyboard", "h", nullptr));
        label_j->setText(QCoreApplication::translate("Keyboard", "j", nullptr));
        label_k->setText(QCoreApplication::translate("Keyboard", "k", nullptr));
        label_l->setText(QCoreApplication::translate("Keyboard", "l", nullptr));
        label_semicolon->setText(QCoreApplication::translate("Keyboard", ";", nullptr));
        label_apostrophe->setText(QCoreApplication::translate("Keyboard", "'", nullptr));
        label_enter->setText(QCoreApplication::translate("Keyboard", "enter", nullptr));
        label_capslock->setText(QCoreApplication::translate("Keyboard", "caps lock", nullptr));
        label_leftshift->setText(QCoreApplication::translate("Keyboard", "shift", nullptr));
        label_z->setText(QCoreApplication::translate("Keyboard", "z", nullptr));
        label_x->setText(QCoreApplication::translate("Keyboard", "x", nullptr));
        label_c->setText(QCoreApplication::translate("Keyboard", "c", nullptr));
        label_v->setText(QCoreApplication::translate("Keyboard", "v", nullptr));
        label_b->setText(QCoreApplication::translate("Keyboard", "b", nullptr));
        label_n->setText(QCoreApplication::translate("Keyboard", "n", nullptr));
        label_m->setText(QCoreApplication::translate("Keyboard", "m", nullptr));
        label_comma->setText(QCoreApplication::translate("Keyboard", ",", nullptr));
        label_dot->setText(QCoreApplication::translate("Keyboard", ".", nullptr));
        label_slash->setText(QCoreApplication::translate("Keyboard", "/", nullptr));
        label_rightshift->setText(QCoreApplication::translate("Keyboard", "shift", nullptr));
        label_leftctrl->setText(QCoreApplication::translate("Keyboard", "ctrl", nullptr));
        label_55->setText(QCoreApplication::translate("Keyboard", "fn", nullptr));
        label_esc->setText(QCoreApplication::translate("Keyboard", "esc", nullptr));
        label_f1->setText(QCoreApplication::translate("Keyboard", "F1", nullptr));
        label_f2->setText(QCoreApplication::translate("Keyboard", "F2", nullptr));
        label_f3->setText(QCoreApplication::translate("Keyboard", "F3", nullptr));
        label_f4->setText(QCoreApplication::translate("Keyboard", "F4", nullptr));
        label_f5->setText(QCoreApplication::translate("Keyboard", "F5", nullptr));
        label_f6->setText(QCoreApplication::translate("Keyboard", "F6", nullptr));
        label_f7->setText(QCoreApplication::translate("Keyboard", "F7", nullptr));
        label_f8->setText(QCoreApplication::translate("Keyboard", "F8", nullptr));
        label_f9->setText(QCoreApplication::translate("Keyboard", "F9", nullptr));
        label_f10->setText(QCoreApplication::translate("Keyboard", "F10", nullptr));
        label_f11->setText(QCoreApplication::translate("Keyboard", "F11", nullptr));
        label_f12->setText(QCoreApplication::translate("Keyboard", "F12", nullptr));
        label_delete->setText(QCoreApplication::translate("Keyboard", "delete", nullptr));
        label_macro->setText(QCoreApplication::translate("Keyboard", "Win", nullptr));
        label_leftalt->setText(QCoreApplication::translate("Keyboard", "alt", nullptr));
        label_space->setText(QString());
        label_rightalt->setText(QCoreApplication::translate("Keyboard", "alt", nullptr));
        label_rightctrl->setText(QCoreApplication::translate("Keyboard", "ctrl", nullptr));
        label_left->setText(QCoreApplication::translate("Keyboard", "left", nullptr));
        label_right->setText(QCoreApplication::translate("Keyboard", "right", nullptr));
        label_up->setText(QCoreApplication::translate("Keyboard", "up", nullptr));
        label_down->setText(QCoreApplication::translate("Keyboard", "down", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Keyboard: public Ui_Keyboard {};
} // namespace Ui

QT_END_NAMESPACE

#endif // KEYBOARDWAVHCT_H
